// Mock database layer — localStorage-backed.
export interface Timestamp { seconds: number; nanoseconds: number; toDate: () => Date; }
function makeTimestamp(ms?: number): Timestamp { const t = ms ?? Date.now(); return { seconds: Math.floor(t / 1000), nanoseconds: (t % 1000) * 1000000, toDate: () => new Date(t) }; }
const MockTimestamp = { fromMillis: (ms: number): Timestamp => makeTimestamp(ms) };
export interface UserProfile { displayName: string; email: string | null; isAnonymous: boolean; createdAt?: Timestamp; onboardingAnswers?: string[]; onboardingComplete?: boolean; }
export interface PetData { name: string; color: string; level: number; xp: number; equippedHat: string | null; equippedClothes: string | null; unlockedItems: string[]; }
export interface SessionData { taskTitle: string; contextText: string; contextImageUrls: string[]; proofImageUrl: string | null; proofText: string; aiTaskDescription: string; xpReward: number; xpPenalty: number; xpChange: number; approved: boolean; completionLevel: 'full' | 'partial' | 'none'; aiFeedback: string; timeEstimate: number; timeActual: number; timerStartedAt?: Timestamp; status: 'active' | 'completed' | 'failed'; timestamp?: Timestamp; isScreenshottable?: boolean; commitmentId?: string; goalTitleSnapshot?: string; }
export interface CommitmentData { title: string; originalInput: string; userDescription?: string; description: string; verificationMethod: 'photo' | 'text' | 'both'; deadline: Timestamp; status: 'active' | 'completed' | 'failed'; xpReward: number; xpPenalty: number; proofImageUrls: string[]; proofText: string; aiFeedback: string; approved: boolean; createdAt?: Timestamp; completedAt?: Timestamp; linkedSessionIds?: string[]; }
interface UserStore { profile?: UserProfile; pet?: PetData; sessions?: Record<string, SessionData>; commitments?: Record<string, CommitmentData>; }
function getStore(uid: string): UserStore { if (typeof window === 'undefined') return {}; try { const raw = localStorage.getItem('capy_db_' + uid); return raw ? JSON.parse(raw) : {}; } catch { return {}; } }
function setStore(uid: string, store: UserStore): void { if (typeof window === 'undefined') return; localStorage.setItem('capy_db_' + uid, JSON.stringify(store)); }
function randomId(): string { return Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2); }
export async function createUserProfile(uid: string, data: { displayName: string; email: string | null; isAnonymous: boolean }): Promise<void> { const store = getStore(uid); store.profile = { ...data, createdAt: makeTimestamp(), onboardingAnswers: [], onboardingComplete: false }; setStore(uid, store); }
export async function getUserProfile(uid: string): Promise<UserProfile | null> { return getStore(uid).profile ?? null; }
export async function updateUserProfile(uid: string, data: Partial<UserProfile>): Promise<void> { const store = getStore(uid); store.profile = { ...store.profile, ...data } as UserProfile; setStore(uid, store); }
export async function createPet(uid: string, data: PetData): Promise<void> { const store = getStore(uid); store.pet = data; setStore(uid, store); }
export async function getPet(uid: string): Promise<PetData | null> { return getStore(uid).pet ?? null; }
export async function updatePet(uid: string, data: Partial<PetData>): Promise<void> { const store = getStore(uid); store.pet = { ...store.pet, ...data } as PetData; setStore(uid, store); }
export async function createSession(uid: string, data: Partial<SessionData>): Promise<string> { const store = getStore(uid); if (!store.sessions) store.sessions = {}; const id = randomId(); store.sessions[id] = { ...data, timestamp: makeTimestamp() } as SessionData; setStore(uid, store); return id; }
export async function getSession(uid: string, sessionId: string): Promise<SessionData | null> { return getStore(uid).sessions?.[sessionId] ?? null; }
export async function updateSession(uid: string, sessionId: string, data: Partial<SessionData>): Promise<void> { const store = getStore(uid); if (!store.sessions) store.sessions = {}; store.sessions[sessionId] = { ...store.sessions[sessionId], ...data } as SessionData; setStore(uid, store); }
export async function getAllSessions(uid: string): Promise<(SessionData & { id: string })[]> { const sessions = getStore(uid).sessions ?? {}; return Object.entries(sessions).map(([id, s]) => ({ id, ...s })).sort((a, b) => (b.timestamp?.seconds ?? 0) - (a.timestamp?.seconds ?? 0)); }
export async function getActiveSessions(uid: string): Promise<(SessionData & { id: string })[]> { return (await getAllSessions(uid)).filter((s) => s.status === 'active'); }
export async function createCommitment(uid: string, data: Partial<CommitmentData>): Promise<string> { const store = getStore(uid); if (!store.commitments) store.commitments = {}; const id = randomId(); store.commitments[id] = { ...data, createdAt: makeTimestamp() } as CommitmentData; setStore(uid, store); return id; }
export async function getCommitment(uid: string, commitmentId: string): Promise<CommitmentData | null> { return getStore(uid).commitments?.[commitmentId] ?? null; }
export async function getAllCommitments(uid: string): Promise<(CommitmentData & { id: string })[]> { const commitments = getStore(uid).commitments ?? {}; return Object.entries(commitments).map(([id, c]) => ({ id, ...c })).sort((a, b) => (b.createdAt?.seconds ?? 0) - (a.createdAt?.seconds ?? 0)); }
export async function updateCommitment(uid: string, commitmentId: string, data: Partial<CommitmentData>): Promise<void> { const store = getStore(uid); if (!store.commitments) store.commitments = {}; store.commitments[commitmentId] = { ...store.commitments[commitmentId], ...data } as CommitmentData; setStore(uid, store); }
export async function deleteCommitment(uid: string, commitmentId: string): Promise<void> { const store = getStore(uid); if (store.commitments) { delete store.commitments[commitmentId]; setStore(uid, store); } }
export const LEVEL_THRESHOLDS = [0, 100, 300, 600, 1000, 1500, 2200, 3000, 4000, 5500];
export function getLevelFromXP(xp: number): number { let level = 1; for (let i = 1; i < LEVEL_THRESHOLDS.length; i++) { if (xp >= LEVEL_THRESHOLDS[i]) level = i + 1; else break; } return level; }
export function getXPForNextLevel(level: number): number { if (level >= LEVEL_THRESHOLDS.length) return LEVEL_THRESHOLDS[LEVEL_THRESHOLDS.length - 1]; return LEVEL_THRESHOLDS[level]; }
export function getXPProgress(xp: number, level: number): { current: number; needed: number; percentage: number } { const cur = LEVEL_THRESHOLDS[level - 1] || 0; const nxt = LEVEL_THRESHOLDS[level] || LEVEL_THRESHOLDS[LEVEL_THRESHOLDS.length - 1]; const current = xp - cur; const needed = nxt - cur; return { current, needed, percentage: Math.min((current / needed) * 100, 100) }; }
export async function applyXPChange(uid: string, xpChange: number, items: { id: string; unlockLevel: number }[]): Promise<{ pet: PetData; leveledUp: boolean; newLevel: number; newUnlocks: string[] }> { const pet = await getPet(uid); if (!pet) throw new Error('Pet not found'); const newXP = Math.max(0, pet.xp + xpChange); const oldLevel = pet.level; const newLevel = Math.max(oldLevel, getLevelFromXP(newXP)); const leveledUp = newLevel > oldLevel; const newUnlocks: string[] = []; const currentUnlocked = new Set(pet.unlockedItems); for (const item of items) { if (item.unlockLevel <= newLevel && !currentUnlocked.has(item.id)) { newUnlocks.push(item.id); currentUnlocked.add(item.id); } } const updatedPet: PetData = { ...pet, xp: newXP, level: newLevel, unlockedItems: Array.from(currentUnlocked) }; await updatePet(uid, updatedPet); return { pet: updatedPet, leveledUp, newLevel, newUnlocks }; }
export async function failOverdueCommitments(uid: string, items: { id: string; unlockLevel: number }[]): Promise<string[]> { const all = await getAllCommitments(uid); const now = Date.now(); const failed: string[] = []; for (const c of all) { if (c.status !== 'active') continue; const dl = c.deadline as unknown as { seconds: number }; const deadlineMs = c.deadline?.toDate?.() ? c.deadline.toDate().getTime() : dl?.seconds ? dl.seconds * 1000 : null; if (deadlineMs === null || deadlineMs > now) continue; await updateCommitment(uid, c.id, { status: 'failed', approved: false, aiFeedback: 'Deadline passed without proof submission.', completedAt: MockTimestamp.fromMillis(now) }); await applyXPChange(uid, -Math.abs(c.xpPenalty), items); failed.push(c.title); } return failed; }
export async function failExpiredSessions(uid: string, items: { id: string; unlockLevel: number }[]): Promise<{ failedSessions: (SessionData & { id: string })[]; validSession: (SessionData & { id: string }) | null }> { const active = await getActiveSessions(uid); const now = Date.now(); const failed: (SessionData & { id: string })[] = []; const valid: (SessionData & { id: string })[] = []; for (const s of active) { const st = s.timerStartedAt as unknown as { seconds: number }; const startMs = s.timerStartedAt?.toDate?.() ? s.timerStartedAt.toDate().getTime() : st?.seconds ? st.seconds * 1000 : null; const expired = startMs === null || now - startMs >= (s.timeEstimate + 60) * 1000; if (expired) { await updateSession(uid, s.id, { status: 'failed', timeActual: s.timeEstimate + 60 }); await applyXPChange(uid, -Math.abs(s.xpPenalty), items); failed.push(s); } else valid.push(s); } if (valid.length > 1) { valid.sort((a, b) => (b.timerStartedAt?.toDate?.()?.getTime() ?? 0) - (a.timerStartedAt?.toDate?.()?.getTime() ?? 0)); for (let i = 1; i < valid.length; i++) { await updateSession(uid, valid[i].id, { status: 'failed', timeActual: valid[i].timeEstimate + 60 }); await applyXPChange(uid, -Math.abs(valid[i].xpPenalty), items); failed.push(valid[i]); } } return { failedSessions: failed, validSession: valid.length > 0 ? valid[0] : null }; }
export async function deleteAccount(uid: string): Promise<void> { if (typeof window !== 'undefined') localStorage.removeItem('capy_db_' + uid); }
export async function resetPet(uid: string, defaultUnlockedItems: string[]): Promise<void> { const pet = await getPet(uid); if (!pet) throw new Error('Pet not found'); await updatePet(uid, { level: 1, xp: 0, equippedHat: null, equippedClothes: null, unlockedItems: defaultUnlockedItems }); await updateUserProfile(uid, { onboardingComplete: false }); }
export async function deleteAllSessions(uid: string): Promise<void> { const store = getStore(uid); store.sessions = {}; setStore(uid, store); }
export async function exportUserData(uid: string): Promise<{ exportedAt: string; profile: UserProfile | null; pet: PetData | null; sessions: (SessionData & { id: string })[]; commitments: (CommitmentData & { id: string })[] }> { return { exportedAt: new Date().toISOString(), profile: await getUserProfile(uid), pet: await getPet(uid), sessions: await getAllSessions(uid), commitments: await getAllCommitments(uid) }; }
