import Link from 'next/link';
import AppShell from '@/components/AppShell';

export default function TermsPage() {
  return (
    <AppShell>
      <div className="min-h-screen bg-[#FFF8F0] p-6 pb-20 md:p-12 relative overflow-hidden">
        {/* Background blobs for visual interest */}
        <div className="absolute top-0 right-0 w-96 h-96 bg-coral/5 rounded-full blur-3xl -z-10 translate-x-1/2 -translate-y-1/2" />
        <div className="absolute bottom-0 left-0 w-[500px] h-[500px] bg-golden/5 rounded-full blur-3xl -z-10 -translate-x-1/4 translate-y-1/4" />

        <div className="max-w-3xl mx-auto relative z-10">
          <Link href="/settings" className="inline-flex items-center text-sm font-medium text-coral hover:text-coral/80 transition-colors mb-8" style={{ fontFamily: 'var(--font-body)' }}>
            ← Back to Settings
          </Link>

          <header className="mb-12">
            <h1 className="text-4xl md:text-5xl font-bold text-near-black mb-4" style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic' }}>
              Terms of Service
            </h1>
            <p className="text-near-black/60 text-sm md:text-base" style={{ fontFamily: 'var(--font-body)' }}>
              Last updated: March 2026
            </p>
          </header>

          <div className="prose prose-stone prose-lg max-w-none text-near-black/80" style={{ fontFamily: 'var(--font-body)', lineHeight: '1.8' }}>
            <p className="lead text-lg mb-8">
              Welcome to Capy! By using our service, you agree to these terms. We&apos;ve kept them as clear as possible so you understand exactly how our AI-powered study accountability app works.
            </p>

            <section className="mb-10 bg-white/40 backdrop-blur-sm p-6 md:p-8 rounded-2xl border border-near-black/5" style={{ boxShadow: 'var(--shadow-sm)' }}>
              <h2 className="text-2xl font-bold text-near-black mb-4" style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic' }}>
                1. The Service
              </h2>
              <p>
                Capy is an AI-powered study accountability app created by Duykha Vu and Subha Karki (TRAAKDEV). The app allows you to commit to study sessions, upload context and proof images, and have your work evaluated by AI (powered by Anthropic&apos;s Claude API) to earn experience points (XP) for your virtual capybara pet.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-near-black mb-4" style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic' }}>
                2. AI Disclaimer & Educational Use
              </h2>
              <p className="mb-4">
                The feedback, verdicts, and completion levels provided by Capy are generated by artificial intelligence. While we strive for accuracy:
              </p>
              <ul className="list-disc pl-6 space-y-2 mb-4">
                <li>AI feedback does not constitute professional, academic, or institutional advice.</li>
                <li>We do not guarantee improved grades or academic outcomes resulting from using Capy.</li>
                <li>The AI may occasionally misunderstand handwriting, context, or complex subject matter.</li>
              </ul>
              <p className="p-4 bg-coral/10 rounded-xl text-coral-dark text-sm border border-coral/20">
                <strong>Important:</strong> Capy is an accountability tool, not an authorized grader. Always rely on your instructors or institutional rubrics for final academic assessment.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-near-black mb-4" style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic' }}>
                3. User Content & Images
              </h2>
              <p className="mb-4">
                When you upload context (like a syllabus or assignment description) and proof (images of your work), you retain full ownership of that content.
              </p>
              <p>
                By uploading this content, you grant Capy the right to process it solely for the purpose of verified study sessions. Your images and text are transmitted securely to Anthropic&apos;s API for evaluation. We explicitly instruct our AI provider <strong>not</strong> to use your data to train their fundamental models.
              </p>
            </section>

            <section className="mb-10 bg-white/40 backdrop-blur-sm p-6 md:p-8 rounded-2xl border border-near-black/5" style={{ boxShadow: 'var(--shadow-sm)' }}>
              <h2 className="text-2xl font-bold text-near-black mb-4" style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic' }}>
                4. Prohibited Uses
              </h2>
              <p className="mb-4">You agree not to use Capy to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Upload sexually explicit, violent, or illegal content.</li>
                <li>Attempt to manipulate, cheat, or intentionally confuse the AI to gain unearned XP (though we respect creative workarounds, blatant system abuse may result in account termination).</li>
                <li>Share accounts or sell high-level capybaras.</li>
                <li>Reverse engineer or attempt to extract the underlying prompts governing the AI&apos;s evaluation logic.</li>
              </ul>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-near-black mb-4" style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic' }}>
                5. Subscriptions & Payments
              </h2>
              <p>
                Capy operates on a freemium model. Basic features are free, while a Capy Pro subscription unlocks advanced AI evaluations, unlimited daily sessions, and exclusive pet items. Subscription fees are billed in advance on a recurring basis. All payments are non-refundable except where required by law.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-near-black mb-4" style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic' }}>
                6. Limitation of Liability
              </h2>
              <p>
                To the maximum extent permitted by law, TRAAKDEV shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of the service.
              </p>
            </section>

            <section className="mb-10">
              <h2 className="text-2xl font-bold text-near-black mb-4" style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic' }}>
                7. Contact Us
              </h2>
              <p>
                If you have any questions about these Terms, you can reach the developers at: <a href="mailto:hello@capyapp.com" className="text-coral hover:underline">hello@capyapp.com</a>.
              </p>
            </section>
          </div>
        </div>
      </div>
    </AppShell>
  );
}
